name: laravel_reverb_example
description: Minimal laravel_reverb example.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  laravel_reverb:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
